name: incremental_dom_bindings
description: Dart bindings for the Incremental DOM library. That's a JS library for updating DOM trees (real DOM, not virtual DOM).
version: 2.1.0+1
homepage: https://www.github.com/blimster/incremental_dom_bindings

environment:
    sdk: ">=2.14.0 <4.0.0"

dev_dependencies:
    build_runner: ^2.1.4
    build_web_compilers: ^3.2.1
    lints: ^1.0.1
    test: ^1.16.0
